Refactor RequestConfig class to fix typo in proxies attribute assignment, fixes: #1034
Clueless-Community/scrape-up pull request #1035
Opened 2024-05-21 15:55 UTC by arpy8

## Description

Fixed the minor typo error in the request_config.py file

## Resolves: #1034

## Checklist

- [x] Have you adhered to the repository's defined coding convention rules?

## Screenshots

![image](https://github.com/Clueless-Community/scrape-up/assets/74809468/707a9274-7d85-4d0d-b17e-bac825446498)

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.

2024-05-22 06:12 UTC, nikhil25803 requested changes
Hey @arpy8 , requested some changes, Address them and let me know.

2024-05-22 06:12 UTC, nikhil25803 commented on src/scrape_up/letterboxd/letterboxd.py
> +        ['Challengers', 'Dune: Part Two', 'The Hunger Games: The Ballad of Songbirds & Snakes', 'BLUE EYE SAMURAI', 'Jaane Jaan']
Instead of list, return in form of dictionary.

2024-05-22 06:12 UTC, nikhil25803 commented on src/scrape_up/letterboxd/letterboxd.py
> +            return e
Return None in case of any exception

2024-05-22 06:12 UTC, nikhil25803 commented on src/scrape_up/letterboxd/letterboxd.py
> +            print(f"An error occurred: {e}")
Remove all the print statement from the code.

2024-05-22 06:12 UTC, nikhil25803 commented on src/scrape_up/letterboxd/letterboxd.py
> +        ['Good Time', 'Beginners', 'Y Tu Mamá También', 'Dogville', 'The House That Jack Built']
Same here, return a dictionary with key-values pairs

2024-05-22 06:12 UTC, nikhil25803 commented on src/scrape_up/letterboxd/letterboxd.py
> +            return None
Also document your module in `dev-documentation.md` file.

2024-05-22 07:30 UTC, arpy8 commented
> Hey @arpy8 , requested some changes, Address them and let me know.

Hi @nikhil25803 , I've made the necessary changes, kindly take a look.
Thanks

2024-05-23 07:27 UTC, nikhil25803 approved these changes

2024-05-23 07:28 UTC, merged

2024-05-23 07:28 UTC, nikhil25803 commented
Great work @arpy8  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅