Automate comment of every PR merge. #1033
Clueless-Community/scrape-up pull request #1055
Opened 2024-05-24 15:42 UTC by Anshika14528

## Description

As soon as a PR merge, a bot will add this message
<img width="909" alt="Screenshot 2024-05-24 at 9 11 41 PM" src="https://github.com/Clueless-Community/scrape-up/assets/168436423/c9b595b8-08d2-4d4d-907c-8ae6e0da34cf">

Great work @{username} !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

## Resolves: [Issue Number]#1003

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2024-05-24 15:45 UTC, Anshika14528 commented
@nikhil25803 sir, can you review this?
Sorry for being late it took me 3 days to figure this out

2024-05-27 09:36 UTC, Anshika14528 commented
@nikhil25803  sir , Can you review this?
and also make sure that you have these function on
<img width="675" alt="Screenshot 2024-05-27 at 3 03 30 PM" src="https://github.com/Clueless-Community/scrape-up/assets/168436423/46b4c649-863a-4f95-881a-9108e24e5523">

2024-06-02 08:37 UTC, Anshika14528 commented
@nikhil25803 sir, please review it and merge it.

2024-06-06 16:21 UTC, nikhil25803 commented
Hey @Anshika14528, test this out it one of your repo and upload a screenshot/video here to validate if it is working.

2024-06-06 16:29 UTC, nikhil25803 requested changes

2024-06-06 16:29 UTC, nikhil25803 commented on .github/workflows/pr_merged.yml
> +    types: [closed]
The type should not be `closed` ideally, I want the message to be sent only if it is merged successfully.

2024-06-06 16:35 UTC, Anshika14528 commented
<img width="385" alt="Screenshot 2024-06-06 at 10 01 51 PM" src="https://github.com/Clueless-Community/scrape-up/assets/168436423/6c3b0efc-30be-4778-a2f6-9a07865b17e8">
It is checking here that if it is merged or not

2024-06-06 16:41 UTC, nikhil25803 approved these changes

2024-06-06 16:41 UTC, merged