added method for getting yearly contributions
Clueless-Community/scrape-up pull request #22
Opened 2023-02-15 17:16 UTC by ayushanand308

2023-02-15 17:40 UTC, nikhil25803 requested changes

2023-02-15 17:40 UTC, nikhil25803 commented on src/scrape_up/github/__init__.py
> +
@ayushanand308, include this PR in the `documentation.md` file.

2023-02-15 17:49 UTC, ayushanand308 commented
@ addded it in documentation but it got pushed as a different pull request. Will it suffice?

2023-02-17 17:12 UTC, nikhil25803 commented
Hey @ayushanand308 , I made some changes to the repository folder structure. Make a Git pull and the method in the `users.py` of  `github` directory of the project.

2023-02-20 14:39 UTC, closed without merging