Added the functions
Clueless-Community/scrape-up pull request #230
Opened 2023-05-29 12:45 UTC by GayathriManeksha

#196

2023-05-30 14:19 UTC, nikhil25803 requested changes
Requested some changes @GayathriManeksha

2023-05-30 14:19 UTC, nikhil25803 commented on src/scrape_up/twitter/numidconverter.py
> +    url = 'https://twitter.com/{}'.format(username)
Hey @GayathriManeksha | The code-base looks good, but please follow the folder structure. 
+ Add `__init__.py` file in the `scrape_up/twitter` directory.
+ You can see the `scrape_up/twitter` directory for reference.
+ Also add the method and class in the `./documentation.md` file.

2023-05-31 07:08 UTC, GayathriManeksha commented
I made the changes mentioned

2023-05-31 07:24 UTC, nikhil25803 commented
Hey, there are some conflicts in the `documentation. md` file, do take a look into it.

2023-05-31 10:50 UTC, GayathriManeksha commented
I have tried resolving the conflicts through the last commits. I guess I have done it right.

2023-06-01 03:33 UTC, nikhil25803 requested changes

2023-06-01 03:33 UTC, nikhil25803 commented on src/scrape_up/twitter/numidconverter.py
> +        return data['author']['additionalName']
Please follow the return format of the project and use try-catch. It's a good practice ✌️
A proper method looks like this as shown in the code below.
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/9024be04-9568-412d-9c00-e4f33a9e692e)

2023-06-01 03:34 UTC, nikhil25803 commented on src/scrape_up/twitter/numidconverter.py
> +        return data['author']['additionalName']
Just a few more changes @GayathriManeksha, else looks good.

2023-06-01 16:15 UTC, GayathriManeksha commented
I also tried resolving the conflicts again

2023-06-05 13:48 UTC, GayathriManeksha commented
@nikhil25803 can you please review this?

2023-06-07 19:01 UTC, nikhil25803 approved these changes

2023-06-07 19:02 UTC, merged

2023-06-07 19:02 UTC, nikhil25803 commented
Looks good @GayathriManeksha 
Do not forget to 
+ Share your work on socials and tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅