internshala
Clueless-Community/scrape-up pull request #241
Opened 2023-05-31 12:16 UTC by patnaikankit

I have scraped Internshala in this commit.

2023-06-01 03:30 UTC, nikhil25803 requested changes

2023-06-01 03:30 UTC, nikhil25803 commented on src/scrape_up/internshala/internships.py
> +                internships.append(internship_data)
Can you upload one  SS of the output? 
Also, update the `documentation. md` file.

2023-06-01 07:42 UTC, patnaikankit commented
![2023-06-01](https://github.com/Clueless-Community/scrape-up/assets/116827173/feb8195c-fc93-478e-a73d-d67673248858)
I have made some changes in the file and it is working now I have attached a ss of the output page.

2023-06-02 07:38 UTC, patnaikankit commented
Hey @nikhil25803 what exactly is the merge conflict about? Is it because I am trying to write over the lines used by someone else?
Please clarify so that I can solve it as soon as possible.

2023-06-07 19:05 UTC, nikhil25803 approved these changes

2023-06-07 19:05 UTC, merged