Stock Price Scraping Support [GSSoC'23]  #221
Clueless-Community/scrape-up pull request #250
Opened 2023-06-01 13:44 UTC by brohithkr

for issue #221 
# Description
This pull request adds the StockPrice class and finance module, which enables scraping stock price for a given stock name and its index(optional). The class provides methods to retrieve latest price of stock and retrieve historical stock prices in given dates range.
Currently the class supports retrieving data for NSE stocks only(can be extended easily).

# Changes Made

- Added StockPrice class with methods for retrieving latest stock price and price of stock for a given range.
- Added NSE class which handles all data requests made for nse stocks

# Documentation -- In Progress
# Known Issues 
- None

# Reviewer Notes
- Please review the implementation and provide feedback on the code structure, logic, and adherence to best practices.
- The module has been designed in such a way that it can be extended to include BSE, NASDAQ and Crypto just by creating the classes. Further work will be done on other stock indexes based on feedback and suggestions for this code.

2023-06-03 19:55 UTC, nikhil25803 requested changes

2023-06-03 19:55 UTC, nikhil25803 commented on src/scrape_up/finance/stock_price.py
> +        return self.stock.get_historical_data(from_date, to_date)
Need some changes 
+ Implement try-catch handling
+ Return method is not as per the codebase, you can check `github` methods for reference.
+ We pass data with a message and error with the same as well.

Implement these changes

2023-06-04 01:45 UTC, brohithkr commented on src/scrape_up/finance/stock_price.py
> +        finally:
Would these changes be okay?

2023-06-04 01:47 UTC, brohithkr commented
![Screenshot 2023-06-04 at 07-08-19 Screenshot from 2023-06-04 07-03-53 png (PNG Image 675 × 286 pixels)](https://github.com/Clueless-Community/scrape-up/assets/71490015/e0113430-7b78-49ff-9c55-320198ffa445)
Would these changes be okay? I just committed them.

2023-06-07 19:08 UTC, merged