IMDB Movies Scraping
Clueless-Community/scrape-up pull request #260
Opened 2023-06-05 19:53 UTC by Shreyg-27

This contains the scraping of the imdb data using beautiful soup. 
#239 Has been resolved. 
Created a class 'Movie' which helps in printing the details of the Top 250 Movies. 
Also extracted the data of the Top 250 movies in an excel file.

2023-06-07 18:36 UTC, nikhil25803 requested changes

2023-06-07 18:36 UTC, nikhil25803 commented on src/scrape_up/imdb1/imdb.py
> +movie = Movie(name=movie_name)
Great work @Shreyg-27 | 
Update the `documentation.md` file about the class and how to use it. You can see other classes mentioned in the same file for reference.

2023-06-09 06:40 UTC, Shreyg-27 commented
Hi, @nikhil25803! 
I have added the content to the documentation.md about the class and how to use it. You can review it once. 
Thank You!

2023-06-09 16:07 UTC, nikhil25803 approved these changes

2023-06-09 16:07 UTC, merged

2023-06-09 16:07 UTC, nikhil25803 commented
Great work buddy @Shreyg-27 !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅