Leetcode Scrapper
Clueless-Community/scrape-up pull request #286
Opened 2023-06-08 21:09 UTC by Hansika002

Issue #259 
Created a Leetcode scrapper.
The code provided is a LeetCodeScraper class that uses Selenium and BeautifulSoup to scrape the rank and rating of a user on the LeetCode website. It initializes a headless Chrome browser using Selenium, navigates to the user's profile page, and retrieves the rank and rating from the HTML using BeautifulSoup. It returns the scraped data along with success or failure messages.

Please review it!!

2023-06-09 15:15 UTC, nikhil25803 requested changes
Requested some changes @Hansika002

2023-06-09 15:15 UTC, nikhil25803 commented on src/scrape_up/leetcode/__init__.py
> +
Hey @Hansika002, the `__init__.py` file is not well scripted. Look for other classes `__init__.py file for reference.

2023-06-09 15:15 UTC, nikhil25803 commented on src/scrape_up/leetcode/leetcode_scraper.py
> +
Add this class and the method in the `documentation.md` file also.

2023-06-09 16:57 UTC, Hansika002 commented
I have made changes to the __init__.py file and also added the documentation in documentation.md file.
New commit - fba285b

Please check it!!

2023-06-10 01:23 UTC, merged

2023-06-10 01:24 UTC, nikhil25803 commented
Great work @Hansika002  !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅