Added Booking.com Scraping
Clueless-Community/scrape-up pull request #334
Opened 2023-06-13 15:44 UTC by koushik395

The method can retrieve all the hotel Names of a destination place at a start date and an end date.

2023-06-13 19:08 UTC, nikhil25803 requested changes

2023-06-13 19:08 UTC, nikhil25803 commented on src/scrape_up/Booking_com/hotels.py
> +
The scraper is taking a lot of time to scrape the data, and optimize it for better accuracy and speed.
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/3ca3aaf6-c49d-4022-9575-511bcb3e111a)

2023-06-14 06:43 UTC, koushik395 commented
@nikhil25803 The requested changes has been commited . Please verify

2023-06-18 06:32 UTC, koushik395 commented
@nikhil25803 please verify as i have optimized the code and please merge it possible.

2023-06-19 14:30 UTC, closed without merging