Get all details of the repositories of the user
Clueless-Community/scrape-up pull request #343
Opened 2023-06-15 21:40 UTC by A15h

This PR solves issue #159 
Get all repo details of user

## Description
> I have done web scraping by using requests, html5lib and beautiful soup library to get details like name, description and link of all Github repositories of the user. I have returned the data so that it can be used by the user. The data includes name, url, description, programming language, stars, issues and pull requests of all the repositories. 

## Checklist
I have performed a self-review of my own code
I have commented my code to understand areas
Kindly mark this contribution under GSSOC' 23
I appreciate your contribution.

2023-06-15 21:41 UTC, A15h commented
Hi @nikhil25803 
I have done the necessary changes. Please tell me if there is any issue that I can work on and if not please merge my PR.
Thank you

2023-06-16 14:57 UTC, nikhil25803 requested changes
Why are you adding it as a file, as it as a method on the `Users` class of the `github` module.

2023-06-18 19:56 UTC, A15h commented
> Why are you adding it as a file, as it as a method on the `Users` class of the `github` module.

Can you please explain what exactly I have to change in my code? I am very confused and am not able to understand. If you could explain it would be very kind of you.

2023-06-22 09:56 UTC, A15h commented
hi @nikhil25803 please reply

2023-06-22 12:16 UTC, nikhil25803 commented
Hey @A15h | Just check this file
https://github.com/Clueless-Community/scrape-up/blob/main/src/scrape_up/github/users.py

2023-06-27 13:10 UTC, nikhil25803 commented
Any update on this PR @A15h?

2023-06-28 02:32 UTC, A15h commented
> Any update on this PR @A15h?

yes i am working on the changes i'll do a new pull request today.

2023-06-29 04:04 UTC, A15h commented
hi @nikhil25803 
do you want me to write different functions for different tasks or just one main function get_all _repo_details?

2023-06-29 05:15 UTC, nikhil25803 requested changes

2023-06-29 05:15 UTC, nikhil25803 commented on issue#159/git_scraper.py
> +import requests
Again, why are you adding it as a separate file? Add it as a method of the `Users` class (of the GitHub module).

Check how the GitHub module is organized and how classes and methods work.

2023-06-29 05:16 UTC, nikhil25803 commented
> hi @nikhil25803 do you want me to write different functions for different tasks or just one main function get_all _repo_details?

Add this as a method of the `Users` class. Got it?

2023-06-29 05:29 UTC, A15h commented
> > hi @nikhil25803 do you want me to write different functions for different tasks or just one main function get_all _repo_details?
> 
> Add this as a method of the `Users` class. Got it?

yes I got it but to get all the repository details i will have to scrape the page of repositories and for that i will have to call another function to scrape the repositories page and then a function which will use this function to get all the details.

2023-06-29 05:33 UTC, nikhil25803 commented
In the `Users` class only, you will find all the methods as per the requirements, try using them only.

You can use an asynchronous approach to make the faster.

2023-06-29 05:54 UTC, closed without merging