GeeksforGeeks Scrapper
Clueless-Community/scrape-up pull request #397
Opened 2023-06-28 05:39 UTC by Juhibhojani

## Description

> Added geeksforgeeks in the src/scrape_up folder and pandas in requirements.txt

## Resolves: [#380 ]

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.
![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/b620d143-fb41-4e44-ae28-c6acf332ca33)

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-06-28 16:07 UTC, nikhil25803 requested changes
Also removed un-necessary packages and dependencies.

2023-06-28 16:07 UTC, nikhil25803 commented on src/scrape_up/geeksforgeeks/geeksforgeeks.py
> +from bs4 import BeautifulSoup
Do not use packages like `pandas`. Simply return the file as `JSON`.

2023-06-28 16:23 UTC, Juhibhojani commented
Done @nikhil25803

2023-06-29 05:11 UTC, nikhil25803 requested changes
The methods are not working on my system, it might not also work on other's.
Please try doing it without selenium, it is possible ig.
Just give it a try

2023-06-29 05:47 UTC, Juhibhojani commented
Can you show me the error it's displaying, that can be helpful as I did try with just beautiful soup at first but it wasn't successful.

2023-06-29 06:22 UTC, Juhibhojani commented
Please try to run the code now, I have made a few changes. @nikhil25803

2023-06-29 07:43 UTC, nikhil25803 submitted a review, later dismissed
Getting this error. look once.

![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/c5acc9c6-2b89-4e80-be77-19c61219668f)

2023-06-29 09:45 UTC, nikhil25803 commented
Hey @Juhibhojani 
The problem is not with your codebase, actually it is related to the `webdriver`. I just checked
To solve this issue, one have to
+ Visit the official ChromeDriver website: https://chromedriver.chromium.org/home
+ Download the compatible version of ChromeDriver for your Chrome browser.
+ Extract the downloaded archive to a suitable location on your system.
+ Add the directory containing the "chromedriver" executable to your system's PATH environment variable.

With this I can not merge this PR, cause I do not the users to must install webdriver on their system.

Look for an alternative, if that works try implementing that else close this PR.

2023-06-30 02:38 UTC, Juhibhojani commented
Yes, I got that and I did try with the requests library but it isn't possible, I can try to download the web driver in the init method, same as leetcode_scrapper. Do you want me to proceed in the same way?  I will try to search for a way around it but I am not sure it will work.

2023-06-30 04:01 UTC, nikhil25803 commented
Give it a try, we will see if that works.

2023-07-01 11:08 UTC, Juhibhojani commented
Due to my on going exams, i am unable to work on this and so this might take a day more.

2023-07-01 19:43 UTC, nikhil25803 commented
No problem @Juhibhojani |

2023-07-02 06:48 UTC, Juhibhojani commented
Hey @nikhil25803 , I have installed ChromeDriverManager in the code itself. Check it out

2023-07-02 11:36 UTC, nikhil25803 reviewed
Code is still not working @Juhibhojani

2023-07-08 04:44 UTC, Juhibhojani commented
@nikhil25803  I have added another argument in options to configure Webdriver. Can you plesase check it out?

2023-07-11 13:02 UTC, nikhil25803 commented
Hey @Juhibhojani | Reviewed the changes you made, it will work on a local machine but not as a package. Also it will create problems while integrating it with the AWS Lambda function.

So can't really merge the PR because of the state it is in.

2023-07-11 17:41 UTC, Juhibhojani commented
Okay, gotcha. So I guess there is nothing I can do here?

2023-07-11 17:43 UTC, Juhibhojani commented
I would love to contribute to this project, I guess will select another webpage that can be scraped without the use of selenium.

2023-07-11 17:52 UTC, nikhil25803 commented
No @Juhibhojani | We already do have a few modules facing the same issue. Add this as a personal project on your GitHub, you must have learned a lot as well throughout this.

We have a few modules which use `bs4` and `beautifulsoup` like Amazon, hashcode, and many others. You should check them out and see if you can add a method to them. Just raise an issue and tag me, and I'll assign you that.

Closing this PR and the corresponding issue for now.

2023-07-11 17:52 UTC, closed without merging

2023-07-12 01:44 UTC, Juhibhojani commented
Okay, Thanks, it was nice working on it.