Adding scraping support for GoodReads platform (GSSoC'23)
Clueless-Community/scrape-up pull request #435
Opened 2023-07-05 15:10 UTC by brohithkr

## Description

This pr adds `BookScraper` class that helps in scraping details of book based on book title and author name or book id from [Goodreads](https://goodreads.com) Platform.  

- `Boookscraper` class has been added in books.py in goodreads folder
- documentation has been updated to reflect corresponding changes
- appropriate error handing mechanisms have been implemented

## Resolves: #347 

## Checklist

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

![image](https://github.com/Clueless-Community/scrape-up/assets/71490015/dc57cdf1-4e6e-4e67-877d-89b38dacc8e3)

## Additional Notes/Comments

None

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-07-05 16:04 UTC, nikhil25803 requested changes

2023-07-05 16:04 UTC, nikhil25803 commented on src/scrape_up/goodreads/books.py
> +from webdriver_manager.chrome import ChromeDriverManager
Hey @brohithkr | `ChromeDriverManager` does not work with the packages on all the devices, it requires installation of the chrome driver. 
Many of our modules are facing the same issue, try to look for an alternative.

2023-07-05 16:11 UTC, nikhil25803 commented on src/scrape_up/goodreads/books.py
> +from webdriver_manager.chrome import ChromeDriverManager
Give it a try

2023-07-05 16:11 UTC, nikhil25803 commented on src/scrape_up/goodreads/books.py
> +from webdriver_manager.chrome import ChromeDriverManager
The problem is, apart from download it needs to be set to the path in system's environment variables.

2023-07-05 16:37 UTC, brohithkr commented on src/scrape_up/goodreads/books.py
>          driver = webdriver.Chrome(
@nikhil25803 I added absolute path of chrome driver so we don't need to change environment variables.

2023-07-05 16:43 UTC, brohithkr commented
@nikhil25803 I added absolute path of driver to webdriver.Chrome() so we dont have to change environment variables

2023-07-05 16:57 UTC, nikhil25803 reviewed
Can't accept the PR, as these many additions will make the page heavier also it won't work because it needs to be installed on `pip`.

The only solution is try finding an alternative to `ChromeDriver`, try the soup generated by `BS4` only.

2023-07-05 17:47 UTC, brohithkr commented
@nikhil25803 But all the modules I imported are already in system requirements. So users will have already installed it using `pip install -r requirements.txt`. Also Goodreads data is behind javascript. So we need selenium to execute the javascript. And also I am just opening the page using selenium and taking the page source after javascript is executed. So I am mostly using bs4. Only place I used selenium to get html after js is executed.

2023-07-07 15:55 UTC, closed without merging

2023-07-07 16:15 UTC, brohithkr commented
hey @nikhil25803 we could do one thing. We could add a script for installling chrome driver and then we can use the chromedriver by the path method. Since selenium is being used by many scripts we could do this so that even other scripts could utilize the chromedriver installed by user.

2023-07-07 18:28 UTC, nikhil25803 commented
This wont work on cloud services.