Added Flipkart t-shirt scrapper
Clueless-Community/scrape-up pull request #471
Opened 2023-07-13 17:01 UTC by jaivsh

## Added Flipkart t-shirt Scrapping class

I've added the FlipkartCloth class, which would scrape the cloth data from the flipkart website. For the purpose of running/executing the functions of the scrapper class, I've created a colaboratory notebook here: https://colab.research.google.com/drive/1WYw5ifia-O2TYH6ocVRK3I3XMZh_RDH7?usp=sharing
This notebook can be used for running the funtions of the scrapper class for testing it. 

## Resolves: #462 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots
The screenshots demonstrating the working of all relevant functions is as follows:

1. scrape():
<img width="1470" alt="Screenshot 2023-07-13 at 10 06 08 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/d9f7af8f-0a77-4c14-b92e-88f8962ec86e">

2. range(): 
<img width="1470" alt="Screenshot 2023-07-13 at 10 07 36 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/cbf4d7f1-017b-425b-b2e2-6e0861caeb6a">

3. minrating():
<img width="1470" alt="Screenshot 2023-07-13 at 10 10 16 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/e22f49b7-3483-4d9c-8264-91a606a37d33">

4. genderfemale(): 
<img width="1470" alt="Screenshot 2023-07-13 at 10 11 31 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/1f48794f-98ba-4321-b237-731ffe8ccf22">

5. size():
<img width="1470" alt="Screenshot 2023-07-13 at 10 20 30 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/a762e861-d87c-44f4-b756-b70498e417ae">

## Additional Notes/Comments

>In flipkart website, the clothes and t-shirts are rendered differently from the rest of the items, as follows:
<img width="1470" alt="Screenshot 2023-07-13 at 10 24 45 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/0222c754-f29b-4620-a324-d14eb5a8807e">

<img width="1470" alt="Screenshot 2023-07-13 at 10 25 05 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/b95b8524-c1b5-4878-800e-17fc6518fba2">

>Because of this difference, the web-scrapping of smartphones or other electronic items becomes entirely different from those of clothing items. Hence, there was nothing in common between the already existing ```Flipkart()``` and the newly added ```FlipkartTees()``` classes. Because of this, I had to create a different class for scraping the clothing accessories from flipkart. 
Thanks!

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-07-13 17:10 UTC, jaivsh commented
@nikhil25803 can u please review this PR?

2023-07-13 17:23 UTC, nikhil25803 requested changes

2023-07-13 17:23 UTC, nikhil25803 commented on src/scrape_up/flipkart/flipkart_file.py
> +class FlipkartTees:
Add this class in a separate file named `flipkart_clothing.py` and add this method to that class. This is the convention we follow, one class in a file.

2023-07-13 17:33 UTC, jaivsh commented
Hi @nikhil25803 I've done the changes suggested by you. Can u please see it now?

2023-07-15 14:15 UTC, nikhil25803 approved these changes

2023-07-15 14:15 UTC, merged