Data Scraping of Bicycles from 'flipkart' [GSSoc'23] #546
Clueless-Community/scrape-up pull request #550
Opened 2023-07-23 19:30 UTC by kanishkasah20

## Description

> I have successfully scraped data of flipkart product bicycles , please review it. PR 2dd9e3c845109f07d1381066afc79ea077965f68

## Resolves: [Issue Number] #546 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [Yes ] Have you adhered to the repository's defined coding convention rules?
- [Yes] Have you updated the 'documentation.md' file with the method/function documentation?
- [Yes ] Have you sent a message along with the result or response?
- [Yes ] Have you used the try-catch technique?
- [Yes ] Has the method/class been added to the documentation (md file)?

## Screenshots
<img width="723" alt="Screenshot 2023-07-23 230454" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/13b8f17d-addf-415f-a11a-76fd93f383e7">

output:
<img width="859" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/cfecfadf-b92f-4f0a-b37b-33dd8fe1b4d3">

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-07-23 19:34 UTC, kanishkasah20 commented
please review it sir @nikhil25803

2023-07-24 17:37 UTC, nikhil25803 requested changes

2023-07-26 08:16 UTC, kanishkasah20 commented on documentation.md
>  organization = github.Organization(organization_name="Clueless-Community")
@nikhil25803 please check changes you requested have been made https://github.com/Clueless-Community/scrape-up/pull/550/commits/ccc919bb9661c16df29560a8d889820294ed3bb2

2023-07-26 15:08 UTC, merged

2023-07-26 15:08 UTC, nikhil25803 commented
Great work @kanishkasah20 !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅