Changed Zomato folder
Clueless-Community/scrape-up pull request #680
Opened 2023-08-06 14:18 UTC by MohanaSrinivas

## Description

> The changes made in this pull request should be briefly described.

#679 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ ] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots

![Screenshot (113)](https://github.com/Clueless-Community/scrape-up/assets/128175768/91bd9caa-53e0-49b9-ad2e-c5d167fbd5b7)

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-08-06 15:24 UTC, nikhil25803 requested changes

2023-08-06 15:24 UTC, nikhil25803 commented on src/scrape_up/__init__.py
What change is this? Do you think it makes any sense?

2023-08-06 16:30 UTC, MohanaSrinivas commented on src/scrape_up/__init__.py
Yah I. Have added some code in zomato folder

2023-08-06 16:31 UTC, nikhil25803 commented on src/scrape_up/__init__.py
Check again in which folder you have added the code?

2023-08-06 16:35 UTC, MohanaSrinivas commented on src/scrape_up/__init__.py
I have initiated pandas library to access zomato 
In __init__.py file

2023-08-06 17:18 UTC, closed without merging

2023-08-07 04:22 UTC, MohanaSrinivas commented on src/scrape_up/__init__.py
![Screenshot 2023-08-07 095014](https://github.com/Clueless-Community/scrape-up/assets/128175768/8f31a34f-5ee0-40a4-a6cb-55b908e010ee)
![Screenshot 2023-08-07 095024](https://github.com/Clueless-Community/scrape-up/assets/128175768/53a0fee1-c3d2-437c-908c-58f4c40c4e44)
@nikhil25803