Fixed codeforces module
Clueless-Community/scrape-up pull request #790
Opened 2023-10-04 14:10 UTC by lazyMonk1010

Refactored the user_get_data method in USER class of codeforces module to correctly fetch the user data from codeforces API. The previous approach had issues with endpoint and the way it is retrieving the data , which should now be resolved with this change.

Fixes #751

## Description

> The changes made in this pull request should be briefly described.

## Resolves: [Issue Number]

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ ] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-10-05 14:27 UTC, nikhil25803 requested changes

2023-10-05 14:27 UTC, nikhil25803 commented on src/scrape_up/codeforces/user.py
> +    api_base_url = "https://codeforces.com/api/"
Do not use APIs @lazyMonk1010 |
We are building an API alternative, so it doesn't make any sense to use API under the hood.
Check if you can fix this module using any scraping library(not selenium or chrome web driver).

2023-10-05 15:00 UTC, lazyMonk1010 commented
Okay I will fix this module

2023-10-06 11:07 UTC, lazyMonk1010 commented
Hey @nikhil25803 I made the changes you asked and used scraping library instead of API

2023-10-09 05:47 UTC, lazyMonk1010 commented
hey @nikhil25803  can you check and merge the pr ,

2023-10-09 12:04 UTC, nikhil25803 commented
Sure, will check it by EOD @lazyMonk1010. 
Sorry, was busy in something.

2023-10-10 13:25 UTC, nikhil25803 approved these changes

2023-10-10 13:47 UTC, merged

2023-10-10 13:47 UTC, nikhil25803 commented
Great work @lazyMonk1010  !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

2023-10-10 15:35 UTC, lazyMonk1010 commented
Thank you @nikhil25803 for merge, glad to contribute. I'll be sure to share it on socials

2023-10-11 05:48 UTC, lazyMonk1010 commented
Hey nikhil! Thankyou so much for merging my pr .
I want to know clueless and your Twitter username.

On Tue, 10 Oct 2023, 19:17 Nikhil Raj, ***@***.***> wrote:

> Great work @lazyMonk1010 <https://github.com/lazyMonk1010> !!
> Do not forget to
>
>    - Share your contribution on socials(twitter mainly), tag us and
>    Clueless 🫂
>    - Give this repository a star ✨
>    - Follow Clueless Community on GitHub ✅
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Clueless-Community/scrape-up/pull/790#issuecomment-1755464558>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCZHPHBCPUOBZM34CW2MCZ3X6VGWTAVCNFSM6AAAAAA5SWVEFOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJVGQ3DINJVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-11 05:53 UTC, nikhil25803 commented
My username -  humans_write
Clueless - by_clueless