Created ESPN Test Queries #819
Clueless-Community/scrape-up pull request #832
Opened 2023-10-15 17:57 UTC by Master-Keshav

## Description

> The changes made in this pull request should be briefly described.

## Resolves: #819 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [X] Have you adhered to the repository's defined coding convention rules?
- [X] Have you updated the 'documentation.md' file with the method/function documentation?
- [X] Have you sent a message along with the result or response?
- [X] Have you used the try-catch technique?
- [X] Has the method/class been added to the documentation (md file)?

## Screenshots
![image](https://github.com/Clueless-Community/scrape-up/assets/69897817/fea9cbb3-b489-4a3f-8a6e-c1d674f7b551)

> Uploading a screenshot illustrating the approach you developed for validation is required.

## Additional Notes/Comments
ESPN Test Queries Created
> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-10-16 18:16 UTC, nikhil25803 requested changes

2023-10-16 18:16 UTC, nikhil25803 commented on src/test/espn_test.py
> +        self.assertIsInstance(scoreboard, list)
Not only check the response instance type, but also check whether it has all the keys or not. 
For example, in the `codechef_test.py` script, we have also checked the key value of the response.
```python
self.assertEqual(
            list(method_response.keys()),
            ["name", "username", "profile_image_link", "rating", "details"],
            "Codechef:get_profile - keys mismatch",
```

2023-10-18 13:45 UTC, nikhil25803 requested changes
The test files are returning errors, please make sure to run the file you are submitting prior to raise an issue.

2023-10-20 16:39 UTC, Master-Keshav commented
> The test files are returning errors, please make sure to run the file you are submitting prior to raise an issue.

In this complete file, I've added comments and documentation to clarify the purpose of each test case and improved error handling by specifying assertions based on the expected data structure. Make sure to replace the date variable with a valid date before running your tests.

2023-10-20 16:40 UTC, Master-Keshav commented
If any other error comes please send me a complete error log. That would be a great help @nikhil25803  
Thanks!

2023-10-20 16:40 UTC, closed without merging