Scraping Dictionarycom for the Word of the Day
Clueless-Community/scrape-up pull request #845
Opened 2023-10-24 07:06 UTC by swetha3456

## Description

Scrapes Dictionary.com for the word of the day and its definition.

## Resolves: #841 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

<img width="596" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/116883043/02ac810e-2468-4394-9d3b-6f61525a227c">

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-10-25 15:03 UTC, nikhil25803 requested changes
Requested some changes @swetha3456.

2023-10-26 14:11 UTC, swetha3456 commented
@nikhil25803, I've made the changes you requested. Please review my PR and suggest further edits if any. Thank you!

2023-10-26 14:42 UTC, nikhil25803 requested changes
Few more changes ...

2023-10-26 14:42 UTC, nikhil25803 commented on src/scrape_up/dictionary/dictionary.py
> +    scraper = IMDB()
`Dictionary` class, not `IMDB` class.

2023-10-26 14:42 UTC, nikhil25803 commented on src/scrape_up/dictionary/dictionary.py
> +        with urlopen("https://www.dictionary.com/") as response:
Each method also do have their docstring, add them as well with syntax and sample response.

2023-10-26 14:42 UTC, nikhil25803 commented on src/scrape_up/dictionary/dictionary.py
> +        return None
Add `exception-handling` in all the methods created to deal with any exception occurred.

2023-10-27 08:25 UTC, swetha3456 commented
Hi @nikhil25803, thanks for pointing out those errors! I've fixed those too. If anything else is left, please let me know.

2023-10-27 10:04 UTC, nikhil25803 approved these changes

2023-10-27 10:04 UTC, merged

2023-10-27 10:04 UTC, nikhil25803 commented
Great work @swetha3456 !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅