adds pinterest - today page and single photo
Clueless-Community/scrape-up pull request #851
Opened 2023-11-11 20:24 UTC by samejima-san

## Description

> I added support to Pinterest, get the today page as well as a extracting images from the page without creating an account.

## Resolves: 850

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-11-16 06:32 UTC, nikhil25803 commented
Go ahead @samejima-san 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

2023-11-16 06:34 UTC, nikhil25803 requested changes

2023-11-16 06:34 UTC, nikhil25803 commented on src/scrape_up/pinterest/pinterest.py
> +            Class - `Pinterest`
Format docstring, check modules like GitHub and IMDB and you'll get an idea about how we format docstring of each mehods.

2023-12-05 10:32 UTC, merged

2023-12-05 11:50 UTC, samejima-san commented
@nikhil25803 no worries good luck with school! 
I can help maintain this project if you need another set of eyes on it.

2023-12-05 14:22 UTC, nikhil25803 commented
Sure @samejima-san, will let you know :))