Add tests for coinmarketcap
Clueless-Community/scrape-up pull request #865
Opened 2023-12-12 12:36 UTC by based-baba

## Description

> Added test file for CoinMarketCap module. 

## Resolves: #856

## Checklist

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you sent a message along with the result or response?

## Screenshots

![image](https://github.com/Clueless-Community/scrape-up/assets/144726228/36bfcda9-6b11-4970-9a5d-05bbc67942b6)

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2023-12-13 03:20 UTC, nikhil25803 requested changes
It seems the test fails, check once again and try to fix the issue. 
(Raise another issue and PR if necessary or you can solve in this PR only, I'll give the combined point in that case)

Error :
```bash
FAIL: test_get_top_cryptocurrencies (__main__.CoinMarketCapTest.test_get_top_cryptocurrencies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\nikhi\OneDrive\Documents\GitHub\scrape-up\src\test\coinmarketcap_test.py", line 22, in test_get_top_cryptocurrencies
    self.assertIsNotNone(top_cryptocurrencies)
AssertionError: unexpectedly None
```

2023-12-13 13:31 UTC, based-baba commented
I used these two lines in order to use the latest fixed version of the `coinmarketcap` module from the git repo instead of the globally installed version which doesn't contain the fix yet.

```py
import sys
sys.path.insert(0, "..")
```

I am not sure what else could be going wrong causing the tests to fail.

2023-12-14 05:49 UTC, nikhil25803 approved these changes

2023-12-14 05:51 UTC, nikhil25803 commented
The changes you made in the `get_top_cryptocurrency()` method are not published in the package manager. Hence it is returning `None`.
Once the new version is published, hopefully, the test will run successfully.

2023-12-14 05:51 UTC, merged