Wuzzuf feature Added
Clueless-Community/scrape-up pull request #923
Opened 2024-05-13 02:57 UTC by msabry1

## Description

## Resolves: #884

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ yes] Have you adhered to the repository's defined coding convention rules?
- [ yes] Have you updated the 'documentation.md' file with the method/function documentation?
- [ yes in the bottom] Have you sent a message along with the result or response?
- [ yes] Have you used the try-catch technique?
- [yes ] Has the method/class been added to the documentation (md file)?

## Screenshots

![image](https://github.com/Clueless-Community/scrape-up/assets/86538943/c89e4149-2e65-4619-bf27-1fb930e60424)

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.

2024-05-13 03:13 UTC, nikhil25803 commented on documentation.md
> +- [Wuzzuf](https://github.com/Clueless-Community/scrape-up/blob/main/documentation.md#Wuzzuf)
In the `documentation.md` file, we maintain the documentation of the modules that are in the deployed version of the package only. 

Remove it from here and include it in `dev-documentation.md` file. Also do not just add link to the location. Also document you modules like this
```js
## Dictionary.com

First create an object of class `Dictionary`.


| Methods          | Details                                                                                      |
| ---------------- | -------------------------------------------------------------------------------------------- |
| `.get_word_of_the_day()`       | Returns the word of the day. |
| `.word_of_the_day_definition()`    | Returns the definition of the word of the day.
--------

```

2024-05-13 03:15 UTC, nikhil25803 commented on documentation.md
> +### How to use :
Remove this how to use section. You can see how other modules are documented. 
You can implement the same way.

2024-05-13 03:16 UTC, nikhil25803 commented on src/scrape_up/wuzzuf/stringdecorator.py
> +def string_decorator(func):
No need of this, just return None in any case the scraper is not able to return the result.
We do create files only for modules.

2024-05-13 03:17 UTC, nikhil25803 commented on src/scrape_up/wuzzuf/wuzzuf.py
> +    """
I renamed the class, but I want you to rephrase the docstring, you can check modules like `GitHub` to see how docstrings are documented.

2024-05-13 03:18 UTC, nikhil25803 requested changes
Hey @msabry1, your code is working fine and returning the desired result. Although few minor changes are required. 

Please address them.

2024-05-13 12:27 UTC, msabry1 commented
@nikhil25803 ok you can review it now 
I changed all you said

2024-05-14 08:59 UTC, nikhil25803 approved these changes

2024-05-14 09:00 UTC, merged

2024-05-14 09:00 UTC, nikhil25803 commented
Great work @msabry1  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅