able tò scape Ambitionbox  website and get compaines with there ratings
Clueless-Community/scrape-up pull request #933
Opened 2024-05-13 07:22 UTC by PlanetDestroyyer

## Description

> The changes made in this pull request should be briefly described.

## Resolves: [Issue Number]

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ ] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

2024-05-13 11:55 UTC, nikhil25803 requested changes

2024-05-13 11:55 UTC, nikhil25803 commented on documentation.md
> +
Add the documentation part in `dev-documentation.md` not in the `documentation.md` file.

2024-05-14 06:36 UTC, PlanetDestroyyer commented
@nikhil25803 i have added changes can review it once

2024-05-14 08:52 UTC, nikhil25803 approved these changes

2024-05-14 08:53 UTC, merged

2024-05-14 08:53 UTC, nikhil25803 commented
Great work @PlanetDestroyyer  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

2024-05-14 08:56 UTC, PlanetDestroyyer commented
Thank you @nikhil25803