Feat: Add MyAnimeList support
Clueless-Community/scrape-up pull request #978
Opened 2024-05-15 06:42 UTC by shravanasati

## Description

This PR adds support for scraping the MyAnimeList anime pages.

## Resolves: #899

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots
![image](https://github.com/Clueless-Community/scrape-up/assets/69118069/4e041dfe-0c3f-4d9d-9b1a-71cc6ab7a8d7)

## Additional Notes/Comments

The code performs the requests only once when the `Anime` class is initialized, and since all the other methods (like title, genres, themes) involve just finding the appropriate elements from the cached page, I've marked them with the `property` decorator indicating that they are cheap to compute.

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.

2024-05-16 17:25 UTC, nikhil25803 requested changes
Hey @shravanasati, add proper docstring to the Classes and methods you have added. You can check modules like `github` and `imdb` for reference on how to format a docstring.

2024-05-16 18:13 UTC, shravanasati commented
alright, done

2024-05-18 05:05 UTC, nikhil25803 approved these changes

2024-05-18 05:05 UTC, merged

2024-05-18 05:06 UTC, nikhil25803 commented
Great work @shravanasati  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅